(Dialog bestplanefitdialog
    (Components
        (PushButton GrabPoints)
        (InputPanel PointsCount)
        (Separator Separator1)
        (Separator Separator2)
        (PushButton CreatePrimitve)
        (PushButton AcceptPrimitive)
    )
    (Resources
        (GrabPoints.Label "Grab Points")
        (GrabPoints.TopOffset 0)
        (GrabPoints.BottomOffset 3)
        (GrabPoints.LeftOffset 0)
        (GrabPoints.RightOffset 0)
        (PointsCount.Columns 7)
        (PointsCount.TopOffset 0)
        (PointsCount.BottomOffset 3)
        (PointsCount.LeftOffset 7)
        (PointsCount.RightOffset 0)
        (PointsCount.InputType 2)
        (PointsCount.Sensitive False)
        (CreatePrimitve.Label "Create Primitive")
        (CreatePrimitve.TopOffset 4)
        (CreatePrimitve.BottomOffset 3)
        (CreatePrimitve.LeftOffset 0)
        (CreatePrimitve.RightOffset 0)
        (AcceptPrimitive.Label "Accept Primitive")
        (AcceptPrimitive.TopOffset 4)
        (AcceptPrimitive.BottomOffset 3)
        (AcceptPrimitive.LeftOffset 7)
        (AcceptPrimitive.RightOffset 0)
        (.Label "Best Plane Fit")
        (.ResourceHints "Version:Creo4")
        (.Resizeable False)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1 0)
                GrabPoints PointsCount Separator1 Separator2 CreatePrimitve AcceptPrimitive
            )
        )
    )
)
