(Dialog ransacdialog
    (Components
        (Tab PrimitivesType PlaneLayout CylinderLayout GeneralLayout)
        (Separator Separator1)
        (SubLayout Layout1)
        (Separator Separator2)
        (SubLayout Layout2)
    )
    (Resources
        (PrimitivesType.Decorated 1)
        (PrimitivesType.Names "Plane" "Cylinder")
        (PrimitivesType.Labels "" "")
        (PrimitivesType.TopOffset 4)
        (PrimitivesType.BottomOffset 0)
        (PrimitivesType.LeftOffset 4)
        (PrimitivesType.RightOffset 4)
        (Separator1.TopOffset 6)
        (Separator1.BottomOffset 6)
        (Separator2.TopOffset 5)
        (Separator2.BottomOffset 5)
        (.Label "Ransac Primitives")
        (.ResourceHints "Version:Creo4")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Resizeable False)
        (.Layout
            (Grid
                (Rows 1 0 0 0 0)
                (Cols 1)
                PrimitivesType Separator1 Layout1 Separator2 Layout2
            )
        )
    )
)
(Layout PlaneLayout
    (Components
        (PushButton PlaneGrabPoints)
        (InputPanel PlanePointCount)
    )
    (Resources
        (PlaneGrabPoints.Label "Grab Points")
        (PlaneGrabPoints.Columns 10)
        (PlaneGrabPoints.TopOffset 0)
        (PlaneGrabPoints.BottomOffset 0)
        (PlaneGrabPoints.LeftOffset 0)
        (PlaneGrabPoints.RightOffset 0)
        (PlanePointCount.TopOffset 0)
        (PlanePointCount.BottomOffset 0)
        (PlanePointCount.LeftOffset 7)
        (PlanePointCount.RightOffset 0)
        (PlanePointCount.Sensitive False)
        (PlanePointCount.InputType 2)
        (.Label "Plane")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 1 0)
                PlaneGrabPoints PlanePointCount
            )
        )
    )
)
(Layout CylinderLayout
    (Components
        (PushButton CylinderGrabPoints)
        (InputPanel CylinderPointCount)
        (PushButton CylinderSelectStartingPoint)
        (InputPanel CylinderStartingPointInfo)
        (PushButton CylinderSelectTerminationPoint)
        (InputPanel CylinderEndingPointInfo)
    )
    (Resources
        (CylinderGrabPoints.Label "Grab Points")
        (CylinderGrabPoints.Columns 10)
        (CylinderGrabPoints.TopOffset 2)
        (CylinderGrabPoints.BottomOffset 2)
        (CylinderGrabPoints.LeftOffset 0)
        (CylinderGrabPoints.RightOffset 0)
        (CylinderPointCount.TopOffset 0)
        (CylinderPointCount.BottomOffset 0)
        (CylinderPointCount.LeftOffset 7)
        (CylinderPointCount.RightOffset 0)
        (CylinderPointCount.Sensitive False)
        (CylinderPointCount.InputType 2)
        (CylinderSelectStartingPoint.Label "Grab Start Point")
        (CylinderSelectStartingPoint.Columns 10)
        (CylinderSelectStartingPoint.TopOffset 2)
        (CylinderSelectStartingPoint.BottomOffset 2)
        (CylinderSelectStartingPoint.LeftOffset 0)
        (CylinderSelectStartingPoint.RightOffset 0)
        (CylinderStartingPointInfo.TopOffset 0)
        (CylinderStartingPointInfo.BottomOffset 0)
        (CylinderStartingPointInfo.LeftOffset 7)
        (CylinderStartingPointInfo.RightOffset 0)
        (CylinderStartingPointInfo.Sensitive False)
        (CylinderSelectTerminationPoint.Label "Grab Termination Point")
        (CylinderSelectTerminationPoint.Columns 10)
        (CylinderSelectTerminationPoint.TopOffset 2)
        (CylinderSelectTerminationPoint.BottomOffset 2)
        (CylinderSelectTerminationPoint.LeftOffset 0)
        (CylinderSelectTerminationPoint.RightOffset 0)
        (CylinderEndingPointInfo.TopOffset 0)
        (CylinderEndingPointInfo.BottomOffset 0)
        (CylinderEndingPointInfo.LeftOffset 7)
        (CylinderEndingPointInfo.RightOffset 0)
        (CylinderEndingPointInfo.Sensitive False)
        (.Label "Cylinder")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1 0)
                CylinderGrabPoints CylinderPointCount CylinderSelectStartingPoint CylinderStartingPointInfo CylinderSelectTerminationPoint CylinderEndingPointInfo
            )
        )
    )
)
(Layout GeneralLayout
    (Components
        (PushButton GrabReferencePlane)
        (InputPanel ReferencePlaneName)
        (PushButton GrabGeneralInnerPoint)
        (InputPanel InnerGeneralPointInfo)
        (PushButton GrabGeneralExtentPoint)
        (InputPanel ExtentGeneralPointInfo)
    )
    (Resources
        (GrabReferencePlane.Label "Grab Reference Plane")
        (GrabReferencePlane.TopOffset 0)
        (GrabReferencePlane.BottomOffset 0)
        (GrabReferencePlane.LeftOffset 0)
        (GrabReferencePlane.RightOffset 0)
        (ReferencePlaneName.Sensitive False)
        (ReferencePlaneName.MaxLen 256)
        (ReferencePlaneName.TopOffset 0)
        (ReferencePlaneName.BottomOffset 0)
        (ReferencePlaneName.LeftOffset 7)
        (ReferencePlaneName.RightOffset 0)
        (GrabGeneralInnerPoint.Label "Grab Inner Point")
        (GrabGeneralInnerPoint.TopOffset 2)
        (GrabGeneralInnerPoint.BottomOffset 2)
        (GrabGeneralInnerPoint.LeftOffset 0)
        (GrabGeneralInnerPoint.RightOffset 0)
        (InnerGeneralPointInfo.Sensitive False)
        (InnerGeneralPointInfo.TopOffset 0)
        (InnerGeneralPointInfo.BottomOffset 0)
        (InnerGeneralPointInfo.LeftOffset 7)
        (InnerGeneralPointInfo.RightOffset 0)
        (GrabGeneralExtentPoint.Label "Grab Extent Point")
        (GrabGeneralExtentPoint.TopOffset 2)
        (GrabGeneralExtentPoint.BottomOffset 2)
        (GrabGeneralExtentPoint.LeftOffset 0)
        (GrabGeneralExtentPoint.RightOffset 0)
        (ExtentGeneralPointInfo.Sensitive False)
        (ExtentGeneralPointInfo.TopOffset 0)
        (ExtentGeneralPointInfo.BottomOffset 0)
        (ExtentGeneralPointInfo.LeftOffset 7)
        (ExtentGeneralPointInfo.RightOffset 0)
        (.Label "General Extrusion")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1 0)
                GrabReferencePlane ReferencePlaneName GrabGeneralInnerPoint InnerGeneralPointInfo GrabGeneralExtentPoint ExtentGeneralPointInfo
            )
        )
    )
)
(Layout Layout1
    (Components
        (Label Label1)
        (Label epsilonlabel)
        (InputPanel epsilon)
        (Label bitmapEpsilonLabel)
        (InputPanel bitmapEpsilon)
        (Label normalThreshLabel)
        (InputPanel normalThresh)
        (Label minSupportLabel)
        (InputPanel minSupport)
        (Label probabilityLabel)
        (InputPanel probability)
    )
    (Resources
        (Label1.Label "Ransac Parameters")
        (Label1.TopOffset 0)
        (Label1.BottomOffset 4)
        (Label1.LeftOffset 0)
        (Label1.RightOffset 0)
        (epsilonlabel.Label "Epsilon")
        (epsilonlabel.Columns 12)
        (epsilonlabel.HelpText "Set distance threshold to a ratio of bounding box width")
        (epsilonlabel.Alignment 0)
        (epsilonlabel.TopOffset 0)
        (epsilonlabel.BottomOffset 7)
        (epsilonlabel.LeftOffset 5)
        (epsilonlabel.RightOffset 30)
        (epsilon.Columns 13)
        (epsilon.HelpText "Set distance threshold to a ratio of bounding box width")
        (epsilon.TopOffset 0)
        (epsilon.BottomOffset 7)
        (epsilon.LeftOffset 0)
        (epsilon.RightOffset 0)
        (epsilon.InputType 3)
        (bitmapEpsilonLabel.Label "Bitmap Epsilon")
        (bitmapEpsilonLabel.Columns 12)
        (bitmapEpsilonLabel.HelpText "set bitmap resolution to .ratio of bounding box width")
        (bitmapEpsilonLabel.Alignment 0)
        (bitmapEpsilonLabel.TopOffset 0)
        (bitmapEpsilonLabel.BottomOffset 7)
        (bitmapEpsilonLabel.LeftOffset 5)
        (bitmapEpsilonLabel.RightOffset 30)
        (bitmapEpsilon.Columns 13)
        (bitmapEpsilon.TopOffset 0)
        (bitmapEpsilon.BottomOffset 7)
        (bitmapEpsilon.LeftOffset 0)
        (bitmapEpsilon.RightOffset 0)
        (bitmapEpsilon.InputType 3)
        (normalThreshLabel.Label "Normal Threshold")
        (normalThreshLabel.Columns 12)
        (normalThreshLabel.HelpText "this is the cos of the maximal normal deviation")
        (normalThreshLabel.Alignment 0)
        (normalThreshLabel.TopOffset 0)
        (normalThreshLabel.BottomOffset 7)
        (normalThreshLabel.LeftOffset 5)
        (normalThreshLabel.RightOffset 30)
        (normalThresh.Columns 13)
        (normalThresh.TopOffset 0)
        (normalThresh.BottomOffset 7)
        (normalThresh.LeftOffset 0)
        (normalThresh.RightOffset 0)
        (normalThresh.InputType 3)
        (minSupportLabel.Label "Minimum support")
        (minSupportLabel.Columns 12)
        (minSupportLabel.HelpText "This is the minimal numer of points required for a primitive")
        (minSupportLabel.Alignment 0)
        (minSupportLabel.TopOffset 0)
        (minSupportLabel.BottomOffset 7)
        (minSupportLabel.LeftOffset 5)
        (minSupportLabel.RightOffset 30)
        (minSupport.Columns 13)
        (minSupport.TopOffset 0)
        (minSupport.BottomOffset 7)
        (minSupport.LeftOffset 0)
        (minSupport.RightOffset 0)
        (minSupport.InputType 2)
        (probabilityLabel.Label "Probability")
        (probabilityLabel.Columns 12)
        (probabilityLabel.HelpText "This is the \"probability\" with which a primitive is overlooked")
        (probabilityLabel.Alignment 0)
        (probabilityLabel.TopOffset 0)
        (probabilityLabel.BottomOffset 7)
        (probabilityLabel.LeftOffset 5)
        (probabilityLabel.RightOffset 30)
        (probability.Columns 13)
        (probability.TopOffset 0)
        (probability.BottomOffset 7)
        (probability.LeftOffset 0)
        (probability.RightOffset 0)
        (probability.InputType 3)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.ButtonAlignment 5516)
        (.Layout
            (Grid
                (Rows 0 1 0 0 0 0)
                (Cols 1 0)
                (Size 1 2)
                Label1 epsilonlabel epsilon bitmapEpsilonLabel bitmapEpsilon normalThreshLabel normalThresh minSupportLabel minSupport probabilityLabel probability
            )
        )
    )
)
(Layout Layout2
    (Components
        (Label Label2)
        (List PrimitiveList)
        (SubLayout Layout3)
    )
    (Resources
        (Label2.Label "Found Primitives")
        (Label2.TopOffset 0)
        (Label2.BottomOffset 5)
        (Label2.LeftOffset 0)
        (Label2.RightOffset 0)
        (PrimitiveList.Columns 29)
        (PrimitiveList.VisibleRows 5)
        (PrimitiveList.TopOffset 0)
        (PrimitiveList.BottomOffset 7)
        (PrimitiveList.LeftOffset 0)
        (PrimitiveList.RightOffset 0)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Label2 PrimitiveList Layout3
            )
        )
    )
)
(Layout Layout3
    (Components
        (PushButton CreatePrimitives)
        (PushButton AcceptPrimitive)
    )
    (Resources
        (CreatePrimitives.Label "Find Primitive")
        (CreatePrimitives.TopOffset 0)
        (CreatePrimitives.BottomOffset 7)
        (CreatePrimitives.LeftOffset 0)
        (CreatePrimitives.RightOffset 0)
        (AcceptPrimitive.Label "Accept Primitive")
        (AcceptPrimitive.TopOffset 0)
        (AcceptPrimitive.BottomOffset 7)
        (AcceptPrimitive.LeftOffset 10)
        (AcceptPrimitive.RightOffset 0)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 0 0)
                CreatePrimitives AcceptPrimitive
            )
        )
    )
)
(MenuPane ransac_cyliinder_popup
    (Components
        (PushButton PrimitiveChangeDirection)
    )
    (Resources
        (PrimitiveChangeDirection.Label "ChangeDirection")
        (PrimitiveChangeDirection.TopOffset 0)
        (PrimitiveChangeDirection.BottomOffset 0)
        (PrimitiveChangeDirection.LeftOffset 0)
        (PrimitiveChangeDirection.RightOffset 0)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
    )
)
