(Dialog sectiondialog
    (Components
        (PushButton GrabReferencePlane)
        (InputPanel GrabbedReferencePlane)
        (Label ThresholdLabel)
        (InputPanel ThresholdInput)
        (Separator Separator1)
        (Separator Separator2)
        (PushButton CreateSectionButton)
    )
    (Resources
        (GrabReferencePlane.Label "Grab Reference Plane")
        (GrabReferencePlane.TopOffset 5)
        (GrabReferencePlane.BottomOffset 0)
        (GrabReferencePlane.LeftOffset 0)
        (GrabReferencePlane.RightOffset 0)
        (GrabbedReferencePlane.Sensitive False)
        (GrabbedReferencePlane.TopOffset 5)
        (GrabbedReferencePlane.BottomOffset 0)
        (GrabbedReferencePlane.LeftOffset 7)
        (GrabbedReferencePlane.RightOffset 5)
        (ThresholdLabel.Label "Projection Threshold")
        (ThresholdLabel.HelpText "Points that fall below this fraction of the sampling density")
        (ThresholdLabel.Alignment 0)
        (ThresholdLabel.TopOffset 0)
        (ThresholdLabel.BottomOffset 0)
        (ThresholdLabel.LeftOffset 0)
        (ThresholdLabel.RightOffset 0)
        (ThresholdInput.TopOffset 5)
        (ThresholdInput.BottomOffset 5)
        (ThresholdInput.LeftOffset 7)
        (ThresholdInput.RightOffset 5)
        (ThresholdInput.InputType 3)
        (CreateSectionButton.Label "Create Section")
        (CreateSectionButton.TopOffset 5)
        (CreateSectionButton.BottomOffset 5)
        (CreateSectionButton.LeftOffset 0)
        (CreateSectionButton.RightOffset 0)
        (.Label "Create Section")
        (.ResourceHints "Version:Creo4")
        (.Resizeable False)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0 0)
                (Cols 1 0)
                GrabReferencePlane GrabbedReferencePlane ThresholdLabel ThresholdInput Separator1 Separator2 CreateSectionButton
            )
        )
    )
)
