(Dialog taubinsmooth
    (Components
        (Label lambda)
        (InputPanel lambdaInput)
        (Label mu)
        (InputPanel muInout)
        (Label iterations)
        (InputPanel iterationsInput)
        (Label gabrielRatio)
        (InputPanel gabrielRatioInput)
        (CheckButton mollification)
        (CheckButton featureSemsitive)
        (Separator Separator1)
        (PushButton Execute)
    )
    (Resources
        (lambda.Label "Lambda")
        (lambda.Columns 10)
        (lambda.Alignment 0)
        (lambda.TopOffset 4)
        (lambda.BottomOffset 0)
        (lambda.LeftOffset 4)
        (lambda.RightOffset 4)
        (lambdaInput.TopOffset 4)
        (lambdaInput.BottomOffset 0)
        (lambdaInput.LeftOffset 0)
        (lambdaInput.RightOffset 4)
        (lambdaInput.InputType 3)
        (mu.Label "Mu")
        (mu.Columns 10)
        (mu.Alignment 0)
        (mu.TopOffset 4)
        (mu.BottomOffset 0)
        (mu.LeftOffset 4)
        (mu.RightOffset 4)
        (muInout.Value "muInput")
        (muInout.TopOffset 4)
        (muInout.BottomOffset 0)
        (muInout.LeftOffset 0)
        (muInout.RightOffset 4)
        (muInout.InputType 3)
        (iterations.Label "Iterations")
        (iterations.Columns 10)
        (iterations.Alignment 0)
        (iterations.TopOffset 4)
        (iterations.BottomOffset 0)
        (iterations.LeftOffset 4)
        (iterations.RightOffset 4)
        (iterationsInput.TopOffset 4)
        (iterationsInput.BottomOffset 0)
        (iterationsInput.LeftOffset 0)
        (iterationsInput.RightOffset 4)
        (iterationsInput.InputType 2)
        (gabrielRatio.Label "Gabriel ratio")
        (gabrielRatio.Columns 10)
        (gabrielRatio.Alignment 0)
        (gabrielRatio.TopOffset 4)
        (gabrielRatio.BottomOffset 0)
        (gabrielRatio.LeftOffset 4)
        (gabrielRatio.RightOffset 4)
        (gabrielRatioInput.TopOffset 4)
        (gabrielRatioInput.BottomOffset 0)
        (gabrielRatioInput.LeftOffset 0)
        (gabrielRatioInput.RightOffset 4)
        (gabrielRatioInput.InputType 3)
        (mollification.Label "Mollification")
        (mollification.TopOffset 4)
        (mollification.BottomOffset 0)
        (mollification.LeftOffset 0)
        (mollification.RightOffset 24)
        (featureSemsitive.Label "Feature Sensitive")
        (featureSemsitive.TopOffset 4)
        (featureSemsitive.BottomOffset 0)
        (featureSemsitive.LeftOffset 0)
        (featureSemsitive.RightOffset 4)
        (Separator1.TopOffset 7)
        (Separator1.BottomOffset 5)
        (Execute.Label "Execute")
        (Execute.Columns 10)
        (Execute.TopOffset 5)
        (Execute.BottomOffset 6)
        (Execute.LeftOffset 0)
        (Execute.RightOffset 0)
        (Execute.ButtonAlignment 4511)
        (.Label "Taubin Smooth")
        (.ResourceHints "Version:Creo4")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 5)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0 0 0 0 0 0)
                (Cols 1 0)
                lambda lambdaInput mu muInout iterations iterationsInput gabrielRatio gabrielRatioInput mollification
                (Pos 6 1)
                featureSemsitive
                (Pos 7 1)
                (Size 1 2)
                Separator1
                (Pos 8 1)
                Execute
            )
        )
    )
)
